version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - fmt_network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "userInputData:1:1"  #  topic:partitions:replication factor
    networks:
      - fmt_network

  listener:
    container_name: listener
    build: 
      context: ListenerService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      KAFKA_TOPIC: "userInputData"
      KAFKA_SERVER: "kafka:9092"
    networks:
      - fmt_network

  parser:
    container_name: parser
    build: 
      context: ParserService
      dockerfile: Dockerfile
    environment:
      BUILD_CONFIGURATION: "Release"
    networks:
      - fmt_network

networks:
  fmt_network:
    driver: bridge
